name: Build Image with PHP

on:
  push:

jobs:
  build:
    uses: vholer/test-ghw-shared/.github/workflows/build.yml@main
    secrets: inherit
    with:
      image: php
    #secrets:
    #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
